### ISSUE TITLE
Safe-eval github critical warning

### ISSUE THREAD

**Issue by drewstone** [hicommonwealth/cw-hq#11]
@filiplazovic I'm getting a critical warning from Github on the package `safe-eval` in the `package-lock.json`. It doesn't seem like we use it, do you know how it got into the package-lock?

**Comment by lazovicff** [comment]
@drewstone Looks like it comes from truffle-core, which is a sub package for truffle: https://github.com/trufflesuite/truffle/blob/develop/packages/truffle-core/package.json#L31

It weird because a stable version of truffle is installed. I will investigate further on this

**Comment by lazovicff** [comment]
@drewstone Its actually `zos`'s outdated `truffle-core`, i will fix those asap
