### ISSUE TITLE
Optimizations for proposal manager and voting interfaces 

### ISSUE THREAD

**Issue by drewstone** [hicommonwealth/cw-hq#3]
An identity council currently contains the following information
- council of trusted members
- set of trusted claims issuers
- history of executions

Currently, there are two contracts: IdentityCouncil and ProposalManager
- IdentityCouncil is responsible for the data
- ProposalManager is responsible for updating the data, submitting proposals, voting, etc.

We let the council members vote on the following
- additions and removals to the council
- additions and removals to the issuers
- executions of function calls on behalf of the IdentityCouncil

What we want to investigate is a minimal implementation with respect to code, storage, and gas usage. This could be by extrapolating the voting logic for any proposal into a common framework and separating it into a library that is deployed separately.

How to make this sustainable with anonymous voting such as the ring signature or snark ballots?

**Comment by lazovicff** [comment]
I would like to work on this. Are you open for outside contributions?

**Comment by drewstone** [comment]
@filiplazovic Thanks for reaching out, unfortunately we're not really working on this anymore (besides the LockDrop.sol)

If you have ideas for optimizations of the LockDrop, we'd love to hear them and are open to ideas/contributions. If you're interested in voting and council management and are open to learning new things, you can checkout what we're currently building for Edgeware. It is all in rust and allows us the ability to take advantage of a larger toolset for doing interesting voting implementations.

In particular, we want to implement voting over identities in:
- [edge-identity](https://github.com/hicommonwealth/edge-identity)

In addition, there are other areas we are looking to implement similar logic (voting/different types of councils) that can be found in these modules.
- [edge-governance](https://github.com/hicommonwealth/edge-governance)
- [edge-delegation](https://github.com/hicommonwealth/edge-delegation)

Some more general issues can be found in this repo as well:
- [edgeware](https://github.com/hicommonwealth/edgeware/issues)

**Comment by lazovicff** [comment]
@drewstone Great, I'm interested in everything, but first, I will start with LockDrop.sol.
